openapi: 3.0.3
info:
  title: XCD Product APIs
  version: '1.0'
  description: >-
    The XCD Product APIs enables seamless integration with the XCD HR & Payroll
    application deployed on a client's Salesforce organization, facilitating HR
    operations such as leave management, expense creation, and timesheet
    submission. Designed for efficiency, the API supports both synchronous and
    asynchronous calls and is optimized for handling large datasets through bulk
    operations.
paths:
  /xcdio__Leave_API__c:
    post:
      tags:
        - Leave
      summary: Book Leave
      operationId: 'BookLeave'
      requestBody:
        description: Book Leave
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/BookLeave'
            example:
              records:
                - xcdio__Leave_Category__c: "Annual Leave"
                  xcdio__Employee_Details__c: "a29Q1000000t6zFIAQ"
                  xcdio__Start_Date__c: "2025-01-10"
                  xcdio__Start_Date_AM_PM_All_Day__c: "All Day"
                  xcdio__End_Date__c: "2025-01-12"
                  xcdio__End_Date_AM_PM_All_Day__c: "All Day"
                - xcdio__Leave_Category__c: "Annual Leave"
                  xcdio__Employee_Details__c: "a29Q1000000t6zFIAQ"
                  xcdio__Start_Date__c: "2025-02-05"
                  xcdio__Start_Date_AM_PM_All_Day__c: "All Day"
                  xcdio__End_Date__c: "2025-02-06"
                  xcdio__End_Date_AM_PM_All_Day__c: "All Day"
                  xcdio__Illness__c: "Other"
              response_fields: "xcdio__Leave_Request__c"
              asynchronous: "false"
              allOrNone: "true"
              
        required: true
      responses:
        '200':
          description: Successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/BookLeaveApiResponseSuccess' 
              example:
                - success: true
                  errors: []
                  xcdio__Leave_Request__c: a10Q100000kS97VIAS
                  Id: a29Q1000000t6zFIAQ
                  record_Sequence: 1
                - success: false
                  errors: ["Sorry, the new Leave/Absence request could not be created as the dates entered for the new Leave/Absence request coincides/overlap with the dates of an existing Leave/Absence. Please confirm the dates and try again for the Role(s):  Dev"]
                  xcdio__Leave_Request__c: null
                  Id: null
                  record_Sequence: 2
        '400':
          description: Request Failed
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/BookLeaveApiResponseFailure' 
              example:
                - success: false
                  errors: ["System.CalloutException: Invalid API Version"]
                  
        '403':
          description: Insufficient Permission
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/BookLeaveApiResponseFailure' 
              example:
                - success: false
                  errors: ["sObject type 'xcdio__Leave_API__c' is not supported. If you are attempting to use a custom object, be sure to append the '__c' after the entity name. Please reference your WSDL or the describe call for the appropriate names."]
        '500':
          description: Internal Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/BookLeaveApiResponseFailure' 
              example:
                - success: false
                  errors: ["NullPointerException: ..."]
        
        default:
          description: Default error sample response
    patch:
      tags:
        - Leave
      summary: Edit & Cancel Leave
      operationId: 'EditLeave'
      requestBody:
        description: Edit & Cancel Leave
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/EditLeave'
            example:
              records:
                - xcdio__Leave_request__c: "a10Q100000iqtztIAA"
                  xcdio__Approval_Status__c: "Cancelled"
                - xcdio__Leave_request__c: "a10Q100000iqtzsIAA"
                  xcdio__Approval_Status__c: "Recalled"
              asynchronous: "false"
              allOrNone: "true"
              
        required: true
      responses:
        '200':
          description: Successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/BookLeaveApiResponseSuccess' 
              example:
                - success: true
                  errors: []
                  xcdio__Leave_Request__c: a10Q100000kS97VIAS
                  Id: a29Q1000000t6zFIAQ
                  record_Sequence: 1
                - success: true
                  errors: []
                  xcdio__Leave_Request__c: a10S900000Mqng1IAB
                  Id: a28S9000000TCAgIAO
                  record_Sequence: 2
        '400':
          description: Request Failed
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/BookLeaveApiResponseFailure' 
              example:
                - success: false
                  errors: ["System.CalloutException: Invalid API Version"]
                  
        '403':
          description: Insufficient Permission
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/BookLeaveApiResponseFailure' 
              example:
                - success: false
                  errors: ["sObject type 'xcdio__Leave_API__c' is not supported. If you are attempting to use a custom object, be sure to append the '__c' after the entity name. Please reference your WSDL or the describe call for the appropriate names."]
        '500':
          description: Internal Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/BookLeaveApiResponseFailure' 
              example:
                - success: false
                  errors: ["NullPointerException: ..."]
        
        default:
          description: Default error sample response
components:
  schemas:
    BookLeave:
      type: object
      properties:
        records:
          type: array
          items:
            $ref: '#/components/schemas/BookLeaveRecordDetail' 
        response_fields:
          type: string
          example: xcdio__Leave_Request__c
        asynchronous:
          type: string
          example: "false"
        allOrNone:
          type: string
          example: "true"
          
    EditLeave:
      type: object
      properties:
        records:
          type: array
          items:
            $ref: '#/components/schemas/EditLeaveRecordDetail' 
        asynchronous:
          type: string
          example: "false"
        allOrNone:
          type: string
          example: "true"
    
    BookLeaveApiResponseSuccess:
      type: object
      properties:
        success:
          type: boolean
          example: "true"
        errors:
          type: array
          items:
            type: string
          example:  []
        xcdio__Leave_Request__c:
          type: string
          example: a10Q100000kS97VIAS
        Id:
          type: string
          example: a29Q1000000t6zFIAQ
        record_Sequence:
          type: integer
          example: 1
          
    BookLeaveApiResponseFailure:
      type: object
      properties:
        success:
          type: boolean
          example: "true"
        errors:
          type: array
          items:
            type: string
          example:  []
    
    BookLeaveRecordDetail:
      type: object
      properties:
        xcdio__Leave_Category__c:
          type: string
          example: Annual Leave
        xcdio__Employee_Details__c:
          type: string
          example: a29Q1000000t6zFIAQ
        xcdio__Start_Date__c:
          type: string
          format: date
          example: '2025-01-10'
        xcdio__Start_Date_AM_PM_All_Day__c:
          type: string
          example: All Day
        xcdio__End_Date__c:
          type: string
          format: date
          example: '2025-01-10'
        xcdio__End_Date_AM_PM_All_Day__c:
          type: string
          example: All Day
        xcdio__Illness__c:
          type: string
          example: Others
    
    EditLeaveRecordDetail:
      type: object
      properties:
        xcdio__Leave_request__c:
          type: string
          example: a10Q100000iqtztIAA
        xcdio__Approval_Status__c:
          type: string
          example: Cancelled
servers:
  - url: https://{mydomain}.my.salesforce.com/services/apexrest/xcdio/xcdapi/v1.0
    variables: {}
tags:
  - name: Leave
    description: 'Book, edit and cancel leave in XCD'
