openapi: 3.0.3
info:
  title: XCD Product APIs
  version: '1.0'
  description: >-
    The XCD Product APIs enable seamless integration with the XCD HR & Payroll
    application deployed in a client's Salesforce organization, facilitating HR
    operations such as leave management, expense creation, and timesheet
    submission. Designed for efficiency, the API supports both synchronous and
    asynchronous calls and is optimized for handling large datasets through bulk
    operations.
paths:
  /xcdio__Leave_API__c:
    post:
      tags:
        - Leave
      summary: Book Leave
      requestBody:
        description: Request to book leave.
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/BookLeave'
            example:
              records:
                - xcdio__Leave_Category__c: "Annual Leave"
                  xcdio__Employee_Details__c: "a29Q1000000t6zFIAQ"
                  xcdio__Start_Date__c: "2025-01-10"
                  xcdio__Start_Date_AM_PM_All_Day__c: "All Day"
                  xcdio__End_Date__c: "2025-01-12"
                  xcdio__End_Date_AM_PM_All_Day__c: "All Day"
                - xcdio__Leave_Category__c: "Annual Leave"
                  xcdio__Employee_Details__c: "a29Q1000000t6zFIAQ"
                  xcdio__Start_Date__c: "2025-02-05"
                  xcdio__Start_Date_AM_PM_All_Day__c: "All Day"
                  xcdio__End_Date__c: "2025-02-06"
                  xcdio__End_Date_AM_PM_All_Day__c: "All Day"
                  xcdio__Illness__c: "Other"
              response_fields: "xcdio__Leave_Request__c"
              asynchronous: "false"
              allOrNone: "true"
      responses:
        '200':
          description: Leave request successfully processed.
        '400':
          description: Request failed due to invalid input.
        '403':
          description: Insufficient permissions.
        '500':
          description: Internal server error.
    patch:
      tags:
        - Leave
      summary: Edit & Cancel Leave
      requestBody:
        description: Request to edit or cancel a leave entry.
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/EditLeave'
      responses:
        '200':
          description: Leave request successfully updated or canceled.
        '400':
          description: Request failed due to validation errors.
        '403':
          description: Insufficient permissions.
        '500':
          description: Internal server error.
components:
  schemas:
    BookLeave:
      type: object
      required:
        - records
      properties:
        records:
          type: array
          description: >-
            A list of leave requests to be created. Each request follows the 
            BookLeaveRecordDetail schema. Every XCD API has a defined limit 
            on the number of records allowed per synchronous request, 
            configured in the "XCD Integration API" custom metadata. 
            Asynchronous requests can contain up to 10,000 records.
          items:
            $ref: '#/components/schemas/BookLeaveRecordDetail'
        response_fields:
          type: string
          description: >-
            A comma-separated list of fields from the API object. Additional 
            fields can be dynamically queried using this parameter.
          example: xcdio__Leave_Request__c, xcdio__Approval_Status__c
        asynchronous:
          type: string
          description: >-
            Defines whether the request is executed synchronously or asynchronously. 
            Synchronous requests return responses immediately. 
            Asynchronous requests return a batch ID, which can be used to check 
            the processing status.
          format: boolean
          default: "false"
        allOrNone:
          type: string
          format: boolean
          default: true
          description: >-
            If set to true, the system allows partial processing of records. 
            If any record fails validation, the rest will still be processed.
    BookLeaveRecordDetail:
      type: object
      properties:
        xcdio__Leave_Category__c:
          type: string
          enum:
            - Annual Leave
            - Sick Leave
          description: The type of leave requested, as defined in XCD HRMS.
        xcdio__Employee_Details__c:
          type: string
          description: The Salesforce record ID of the employee requesting leave.
        xcdio__Start_Date__c:
          type: string
          format: date
          description: The start date of the leave period.
        xcdio__Start_Date_AM_PM_All_Day__c:
          type: string
          enum:
            - AM
            - PM
            - All Day
          description: >-
            Specifies whether the leave starts in the morning (AM), afternoon (PM), 
            or spans the entire day (All Day).
        xcdio__End_Date__c:
          type: string
          format: date
          description: The end date of the leave period.
        xcdio__End_Date_AM_PM_All_Day__c:
          type: string
          enum:
            - AM
            - PM
            - All Day
          description: >-
            Specifies whether the leave ends in the morning (AM), afternoon (PM), 
            or spans the entire day (All Day).
        xcdio__Illness__c:
          type: string
          enum:
            - Back & neck
            - Chest & respiratory
            - Covid-19 confirmed
            - Covid-19 suspected
            - Covid-19 self-isolating
            - Diabetes
            - Eyes, ear, nose, mouth
            - Genito-urinary
            - Heart
            - Infection
            - Musculo-skeletal
            - Neurological
            - Pregnancy
            - Stomach
            - Stress
            - Other
          description: >-
            Applicable only for sick leave. The list of values may vary based on 
            client-specific customizations.
    EditLeave:
      type: object
      required:
        - records
      properties:
        records:
          type: array
          description: >-
            A list of leave requests to be edited or canceled. Each request 
            follows the EditLeaveRecordDetail schema. The request limit is 
            defined in the "XCD Integration API" custom metadata. 
            Asynchronous requests can contain up to 10,000 records.
          items:
            $ref: '#/components/schemas/EditLeaveRecordDetail'
        asynchronous:
          type: string
          description: >-
            Defines whether the request is executed synchronously or asynchronously.
            Synchronous requests return responses immediately. 
            Asynchronous requests return a batch ID, which can be used to check 
            the processing status.
          format: boolean
          default: "false"
        allOrNone:
          type: string
          format: boolean
          default: true
          description: >-
            If set to true, the system allows partial processing of records. 
            If any record fails validation, the rest will still be processed.
    EditLeaveRecordDetail:
      type: object
      properties:
        xcdio__Leave_request__c:
          type: string
          description: The Salesforce record ID of the leave request to be modified.
        xcdio__Approval_Status__c:
          type: string
          description: The updated approval status (e.g., "Cancelled").
servers:
  - url: https://{mydomain}.my.salesforce.com/services/apexrest/xcdio/xcdapi/v1.0
tags:
  - name: Leave
    description: Book, edit, and cancel leave in XCD.
